[package]
name = "silent-whistle-core"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.10.10"
chrono = { version = "0.4.38", features = ["serde"] }
risc0-zkvm = "1.1.2"
serde = { version = "1.0.213", features = ["derive"] }
