// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
// use silent_whistle_risc0::methods::{
//     FACT_PROOF_GENERATOR_ELF, FACT_PROOF_GENERATOR_ID
// };
use risc0_zkvm::{default_prover, ExecutorEnv};
use silent_whistle_core::{ProofInput, Proof};

// fn setup_tracing() {
//     tracing_subscriber::fmt()
//         .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
//         .init();
// }

const FACT_PROOF_GENERATOR_ELF: &[u8] = &[];
const FACT_PROOF_GENERATOR_ID: [u8; 32] = [0; 32];

pub fn prove(input: ProofInput) -> Proof {
    // Write input to the environment and build it.
    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();

    // Create default prover (local?)
    let prover = default_prover();

    //
    let prove_info = prover
        .prove(env, FACT_PROOF_GENERATOR_ELF)
        .unwrap();

    let receipt = prove_info.receipt;
    Proof {
        receipt
    }
}

pub fn verify(input: Proof) -> bool {
    // setup_tracing();

    match input
        .receipt
        .verify(FACT_PROOF_GENERATOR_ID) {
            Ok(_) => true,
            Err(_) => false,
        }
}
