[package]
name = "guest_code"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "1.1.1", default-features = false, features = ['std'] }
silent-whistle-core = { path = "../../../silent-whistle-core" }
